FROM ruby:3.1.2

ENV PORT 3000
EXPOSE $PORT

WORKDIR /home/app

RUN apt-get update && apt-get install -y npm && npm install -g yarn

COPY Gemfile Gemfile.lock ./
RUN bundle install
COPY . .

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["rails", "server", "-e", "production", "-p", "3000"]
